export {default as Intro} from './intro'
export {default as About} from './about'
export {default as Goals} from './goals'
export {default as CustomSlider} from './slider'
export {default as Joleen} from './jo'
export {default as Rachael} from './ray'