export {default as Info} from './info'
export {default as Video} from './video'
export {default as Element} from './element'
export {default as Goal} from './goal'
export {default as Value} from './value'
export {default as Address} from './address'
export {default as Patner} from './patner'
export {default as CustomIcon} from './customicon'